# Generated by Django 5.2 on 2025-05-10 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('courriel', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateField()),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.reader')),
            ],
        ),
    ]
