# Generated by Django 5.2 on 2025-05-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_reader_comment_delete_generalcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='courriel',
            new_name='Email',
        ),
    ]
