# Generated by Django 5.2 on 2025-05-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_courriel_reader_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='comment',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='first_name',
            new_name='Lirst_name',
        ),
    ]
