# Generated by Django 5.2 on 2025-05-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_comment_reader_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='Lirst_name',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='last_name',
            new_name='Last_name',
        ),
    ]
